name: Scrape Urls

# [1] Yudono Ski Resort Road Conditions
# Source: https://www.thr.mlit.go.jp/yamagata/camera-road/point.html
# Target: https://www2.thr.mlit.go.jp/Bumon/J76301/livecam/cctv016.jpg
# Output: data/yudono-road-conditions.jpg

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write # Permission to push commits to default token

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with: ${{ github.head_ref }}

      - name: Download image
        run: |
          mkdir -p data
          curl -L "https://www2.thr.mlit.go.jp/Bumon/J76301/livecam/cctv016.jpg" -o data/yudono-road-conditions.jpg
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/yudono-road-conditions.jpg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update scraped urls" && git push)