name: Scrape Urls

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download image
        run: |
          mkdir -p data
          curl -L "https://www2.thr.mlit.go.jp/Bumon/J76301/livecam/cctv016.jpg" -o data/yudono-road-conditions.jpg
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git data/yudono-road-conditions.jpg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update scraped urls" && git push)